In [15]:
import pandas as pd
df = pd.read_csv('dados_apartamentos.csv')

In [16]:
df.head(40)

,Unnamed: 0,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,cidade,data_scraping
0,0,180,"Rua Senador Euzebio, 6 - Flamengo, Rio de Jane...",3 Quartos,2 Banheiros,1 Vaga,R$ 3.750 /mês,R$ 1.650,Aceita animais\nAr-condicionado\nEspaço gourme...,Rio de Janeiro,"September 20, 2021 16:22"
1,1,105,"Rua São Clemente, 117 - Botafogo, Rio de Janei...",3 Quartos,3 Banheiros,2 Vagas,R$ 3.500 /mês,R$ 2.480,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Rio de Janeiro,"September 20, 2021 16:22"
2,2,80,"Rua Pereira da Silva, 444 - Laranjeiras, Rio d...",2 Quartos,1 Banheiro,-- Vaga,R$ 2.000 /mês,R$ 762,Playground\nPortão eletrônico,Rio de Janeiro,"September 20, 2021 16:22"
3,3,58,"Rua Carvalho Alvim, 654 - Tijuca, Rio de Janei...",2 Quartos,3 Banheiros,1 Vaga,R$ 1.800 /mês,R$ 912,Churrasqueira\nPiscina\nPlayground\nSalão de f...,Rio de Janeiro,"September 20, 2021 16:22"
4,4,70,"Rua Tirol, 962 - Freguesia- Jacarepaguá, Rio d...",3 Quartos,2 Banheiros,1 Vaga,R$ 1.400 /mês,R$ 900,Churrasqueira\nElevador\nCondomínio fechado\nA...,Rio de Janeiro,"September 20, 2021 16:22"
5,5,62,"Rua Paissandu, 179 - Flamengo, Rio de Janeiro ...",2 Quartos,2 Banheiros,-- Vaga,R$ 2.000 /mês,R$ 864,Elevador\nAceita animais\nJardim\nPlayground\n...,Rio de Janeiro,"September 20, 2021 16:22"
6,6,40,"Avenida Nossa Senhora de Copacabana, 1004 - Co...",1 Quarto,1 Banheiro,-- Vaga,R$ 1.499 /mês,R$ 400,Ar-condicionado\nCozinha americana\nMobiliado\...,Rio de Janeiro,"September 20, 2021 16:22"
7,7,50,"Rua Assis Bueno, 46 - Botafogo, Rio de Janeiro...",2 Quartos,2 Banheiros,1 Vaga,R$ 1.950 /mês,R$ 974,Piscina\nElevador\nAcademia\nAceita animais\nB...,Rio de Janeiro,"September 20, 2021 16:22"
8,8,114,"Rua Engenheiro Cortes Sigaud, 191 - Leblon, Ri...",3 Quartos,3 Banheiros,1 Vaga,R$ 5.600 /mês,R$ 2.080,Elevador\nAceita animais\nAr-condicionado\nSal...,Rio de Janeiro,"September 20, 2021 16:22"
9,9,36,"Rua do Bispo, 265 - Tijuca, Rio de Janeiro - RJ",1 Quarto,1 Banheiro,-- Vaga,R$ 1.000 /mês,R$ 540,Aceita animais\nElevador\nPortão eletrônico\nP...,Rio de Janeiro,"September 20, 2021 16:22"
10,10,64,"Rua Sorocaba, 231 - Botafogo, Rio de Janeiro - RJ",2 Quartos,2 Banheiros,1 Vaga,R$ 3.100 /mês,R$ 800,Piscina\nChurrasqueira\nAcademia\nAceita anima...,Rio de Janeiro,"September 20, 2021 16:22"
11,11,32,"Estrada do Rio Grande, 407 - Taquara, Rio de J...",1 Quarto,1 Banheiro,1 Vaga,R$ 790 /mês,NaN,Aceita animais\nPortão eletrônico,Rio de Janeiro,"September 20, 2021 16:22"
12,12,50,"Rua Visconde de Pirajá, 571 - Ipanema, Rio de ...",1 Quarto,1 Banheiro,-- Vaga,R$ 1.850 /mês,R$ 613,Ar-condicionado\nAceita animais\nElevador\nPor...,Rio de Janeiro,"September 20, 2021 16:22"
13,13,70,"Rua Tomás Lopes, 739 - Penha Circular, Rio de ...",2 Quartos,1 Banheiro,-- Vaga,R$ 1.000 /mês,R$ 303,Aceita animais\nPortão eletrônico,Rio de Janeiro,"September 20, 2021 16:22"
14,14,80,"Avenida General San Martin, 900 - Leblon, Rio ...",2 Quartos,2 Banheiros,1 Vaga,R$ 3.500 /mês,R$ 1.445,Elevador\nAceita animais\nAr-condicionado\nPor...,Rio de Janeiro,"September 20, 2021 16:22"
15,15,84,"Rua Figueiredo Magalhães, 848 - Copacabana, Ri...",2 Quartos,2 Banheiros,-- Vaga,R$ 2.550 /mês,R$ 780,Elevador\nCondomínio fechado\nAceita animais\n...,Rio de Janeiro,"September 20, 2021 16:22"
16,16,32,"Rua Haddock Lobo, 11 - Estacio, Rio de Janeiro...",1 Quarto,1 Banheiro,-- Vaga,R$ 700 /mês,R$ 334,NaN,Rio de Janeiro,"September 20, 2021 16:22"
17,17,77,"Rua Prudente de Morais, 368 - Ipanema, Rio de ...",2 Quartos,2 Banheiros,1 Vaga,R$ 4.800 /mês,R$ 1.880,Piscina\nMobiliado\nElevador\nAcademia\nAr-con...,Rio de Janeiro,"September 20, 2021 16:22"
18,18,30,"Avenida Nossa Senhora de Copacabana, 1045 - Co...",1 Quarto,1 Banheiro,-- Vaga,R$ 1.500 /mês,R$ 590,Aceita animais\nElevador\nCondomínio fechado\n...,Rio de Janeiro,"September 20, 2021 16:22"
19,19,70,"Avenida São Josemaria Escrivá, 560 - Itanhangá...",2 Quartos,1 Banheiro,1 Vaga,R$ 1.100 /mês,R$ 650,Piscina\nElevador\nCondomínio fechado\nAceita ...,Rio de Janeiro,"September 20, 2021 16:22"
20,20,73,"Rua Marechal Pires Ferreira, 10 - Cosme Velho,...",1 Quarto,1 Banheiro,1 Vaga,R$ 2.750 /mês,R$ 673,Elevador\nCondomínio fechado\nAcademia\nAceita...,Rio de Janeiro,"September 20, 2021 16:22"
21,21,45,"Rua Leopoldo Miguez, 174 - Copacabana, Rio de ...",1 Quarto,1 Banheiro,-- Vaga,R$ 1.300 /mês,R$ 970,Elevador\nCondomínio fechado\nPortaria 24h\nPo...,Rio de Janeiro,"September 20, 2021 16:22"
22,22,180,"Rua Almirante Tamandaré, 36 - Flamengo, Rio de...",3 Quartos,2 Banheiros,1 Vaga,R$ 2.900 /mês,R$ 1.750,Condomínio fechado\nPortão eletrônico\nPortari...,Rio de Janeiro,"September 20, 2021 16:22"
23,23,239,"Rua Joaquim Nabuco, 266 - Ipanema, Rio de Jane...",3 Quartos,5 Banheiros,3 Vagas,R$ 22.900 /mês,R$ 3.465,Mobiliado\nElevador\nAceita animais\nAr-condic...,Rio de Janeiro,"September 20, 2021 16:22"
24,24,65,"Rua Sá Ferreira, 127 - Copacabana, Rio de Jane...",2 Quartos,1 Banheiro,-- Vaga,R$ 1.650 /mês,R$ 1.200,Elevador\nBicicletário\nPortaria 24h,Rio de Janeiro,"September 20, 2021 16:22"
25,25,70,"Avenida das Américas, 17450 - Recreio Dos Band...",2 Quartos,2 Banheiros,2 Vagas,R$ 2.100 /mês,R$ 865,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Rio de Janeiro,"September 20, 2021 16:22"
26,26,44,"Rua Visconde de Pirajá, 247 - Ipanema, Rio de ...",1 Quarto,1 Banheiro,1 Vaga,R$ 2.500 /mês,R$ 1.000,Ar-condicionado\nElevador,Rio de Janeiro,"September 20, 2021 16:22"
27,27,108,"Avenida Oswaldo Cruz, 99 - Flamengo, Rio de Ja...",2 Quartos,3 Banheiros,1 Vaga,R$ 3.500 /mês,R$ 739,Ar-condicionado\nPlayground\nSalão de festas\n...,Rio de Janeiro,"September 20, 2021 16:22"
28,28,70,"Avenida Nossa Senhora de Copacabana, 249 - Cop...",2 Quartos,2 Banheiros,1 Vaga,R$ 3.000 /mês,R$ 737,Elevador\nCondomínio fechado\nAceita animais\n...,Rio de Janeiro,"September 20, 2021 16:22"
29,29,131,"Rua das Laranjeiras, 91 - Laranjeiras, Rio de ...",3 Quartos,3 Banheiros,1 Vaga,R$ 3.900 /mês,R$ 1.045,Elevador\nCondomínio fechado\nAceita animais\n...,Rio de Janeiro,"September 20, 2021 16:22"
30,30,170,"Rua Raimundo Correia - Copacabana, Rio de Jane...",4 Quartos,4 Banheiros,1 Vaga,R$ 2.500 /mês,R$ 3.165,Ar-condicionado\nCloset\nElevador\nPortaria 24h,Rio de Janeiro,"September 20, 2021 16:22"
31,31,140,"Rua Conselheiro Lafaiete, 32 - Copacabana, Rio...",3 Quartos,2 Banheiros,-- Vaga,R$ 3.500 /mês,R$ 1.200,Aceita animais\nPortão eletrônico\nPortaria 24h,Rio de Janeiro,"September 20, 2021 16:22"
32,32,75,"Rua Barão de Itapagipe, 452 - Tijuca, Rio de J...",2 Quartos,2 Banheiros,1 Vaga,R$ 1.750 /mês,R$ 888,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Rio de Janeiro,"September 20, 2021 16:22"
33,33,85,"Rua Frederico Quartarolli, 43 - Recreio Dos Ba...",3 Quartos,2 Banheiros,1 Vaga,R$ 4.000 /mês,R$ 555,Mobiliado\nElevador\nCondomínio fechado\nVaran...,Rio de Janeiro,"September 20, 2021 16:22"
34,34,70,"Rua Siqueira Campos, 170 - Copacabana, Rio de ...",2 Quartos,2 Banheiros,1 Vaga,R$ 2.500 /mês,R$ 895,Acesso para deficientes\nElevador\nPortão elet...,Rio de Janeiro,"September 20, 2021 16:22"
35,35,67,"Rua Paula Matos, 52 - Santa Teresa, Rio de Jan...",2 Quartos,1 Banheiro,-- Vaga,R$ 1.500 /mês,R$ 460,Aceita animais,Rio de Janeiro,"September 20, 2021 16:22"
36,36,170,"Rua Cayowaá, 425 - Perdizes, São Paulo - SP",4 Quartos,5 Banheiros,3 Vagas,R$ 9.500 /mês,R$ 2.200,Piscina\nMobiliado\nChurrasqueira\nElevador\nA...,São Paulo,"September 20, 2021 16:22"
37,37,65,"Rua Caiubi, 1322 - Perdizes, São Paulo - SP",3 Quartos,2 Banheiros,1 Vaga,R$ 2.800 /mês,R$ 800,Salão de festas\nPiscina\nBicicletário\nElevad...,São Paulo,"September 20, 2021 16:22"
38,38,70,"Rua Álvaro de Carvalho, 134 - Centro, São Paul...",2 Quartos,2 Banheiros,1 Vaga,R$ 2.100 /mês,R$ 780,Piscina\nChurrasqueira\nElevador\nCondomínio f...,São Paulo,"September 20, 2021 16:22"
39,39,56,"Rua Jaraguá, 737 - Bom Retiro, São Paulo - SP",2 Quartos,2 Banheiros,1 Vaga,R$ 2.400 /mês,R$ 430,Piscina\nElevador\nCondomínio fechado\nVaranda...,São Paulo,"September 20, 2021 16:22"

In [17]:
df = df.drop(['Unnamed: 0', 'data_scraping'],axis=1)

In [18]:
df['vagas'] = df['vagas'].str.extract('(.*) Vaga')
df['banheiros'] = df['banheiros'].str.extract('(.*) Banheiro')
df['quartos'] = df['quartos'].str.extract('(.*) Quarto')
df.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,cidade
0,180,"Rua Senador Euzebio, 6 - Flamengo, Rio de Jane...",3,2,1,R$ 3.750 /mês,R$ 1.650,Aceita animais\nAr-condicionado\nEspaço gourme...,Rio de Janeiro
1,105,"Rua São Clemente, 117 - Botafogo, Rio de Janei...",3,3,2,R$ 3.500 /mês,R$ 2.480,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Rio de Janeiro
2,80,"Rua Pereira da Silva, 444 - Laranjeiras, Rio d...",2,1,--,R$ 2.000 /mês,R$ 762,Playground\nPortão eletrônico,Rio de Janeiro
3,58,"Rua Carvalho Alvim, 654 - Tijuca, Rio de Janei...",2,3,1,R$ 1.800 /mês,R$ 912,Churrasqueira\nPiscina\nPlayground\nSalão de f...,Rio de Janeiro
4,70,"Rua Tirol, 962 - Freguesia- Jacarepaguá, Rio d...",3,2,1,R$ 1.400 /mês,R$ 900,Churrasqueira\nElevador\nCondomínio fechado\nA...,Rio de Janeiro

In [19]:
df['preco'] = df['preco'].str.extract('R\$ (.*) /mês') 
df['condominio'] = df['condominio'].str.extract('R\$ (.*)')
df.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,cidade
0,180,"Rua Senador Euzebio, 6 - Flamengo, Rio de Jane...",3,2,1,3.750,1.650,Aceita animais\nAr-condicionado\nEspaço gourme...,Rio de Janeiro
1,105,"Rua São Clemente, 117 - Botafogo, Rio de Janei...",3,3,2,3.500,2.480,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Rio de Janeiro
2,80,"Rua Pereira da Silva, 444 - Laranjeiras, Rio d...",2,1,--,2.000,762,Playground\nPortão eletrônico,Rio de Janeiro
3,58,"Rua Carvalho Alvim, 654 - Tijuca, Rio de Janei...",2,3,1,1.800,912,Churrasqueira\nPiscina\nPlayground\nSalão de f...,Rio de Janeiro
4,70,"Rua Tirol, 962 - Freguesia- Jacarepaguá, Rio d...",3,2,1,1.400,900,Churrasqueira\nElevador\nCondomínio fechado\nA...,Rio de Janeiro

In [20]:
df['preco'] = df['preco'].replace('\.','',regex=True)
df['condominio'] = df['condominio'].replace('\.','',regex=True)
df.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,cidade
0,180,"Rua Senador Euzebio, 6 - Flamengo, Rio de Jane...",3,2,1,3750,1650,Aceita animais\nAr-condicionado\nEspaço gourme...,Rio de Janeiro
1,105,"Rua São Clemente, 117 - Botafogo, Rio de Janei...",3,3,2,3500,2480,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Rio de Janeiro
2,80,"Rua Pereira da Silva, 444 - Laranjeiras, Rio d...",2,1,--,2000,762,Playground\nPortão eletrônico,Rio de Janeiro
3,58,"Rua Carvalho Alvim, 654 - Tijuca, Rio de Janei...",2,3,1,1800,912,Churrasqueira\nPiscina\nPlayground\nSalão de f...,Rio de Janeiro
4,70,"Rua Tirol, 962 - Freguesia- Jacarepaguá, Rio d...",3,2,1,1400,900,Churrasqueira\nElevador\nCondomínio fechado\nA...,Rio de Janeiro

In [27]:
df_sp = df[df.cidade != 'Rio de Janeiro']

In [28]:
# Se quiser excluir um dataframe, rode del <dataframe>

In [29]:
df_sp.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,cidade
36,170,"Rua Cayowaá, 425 - Perdizes, São Paulo - SP",4,5,3,9500,2200,Piscina\nMobiliado\nChurrasqueira\nElevador\nA...,São Paulo
37,65,"Rua Caiubi, 1322 - Perdizes, São Paulo - SP",3,2,1,2800,800,Salão de festas\nPiscina\nBicicletário\nElevad...,São Paulo
38,70,"Rua Álvaro de Carvalho, 134 - Centro, São Paul...",2,2,1,2100,780,Piscina\nChurrasqueira\nElevador\nCondomínio f...,São Paulo
39,56,"Rua Jaraguá, 737 - Bom Retiro, São Paulo - SP",2,2,1,2400,430,Piscina\nElevador\nCondomínio fechado\nVaranda...,São Paulo
40,65,"Rua Piracuama, 417 - Perdizes, São Paulo - SP",2,1,2,1700,800,Piscina\nElevador\nAceita animais\nJardim\nSal...,São Paulo

In [30]:
df_sp = df_sp.drop(['cidade'],axis=1)
df_sp.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades
36,170,"Rua Cayowaá, 425 - Perdizes, São Paulo - SP",4,5,3,9500,2200,Piscina\nMobiliado\nChurrasqueira\nElevador\nA...
37,65,"Rua Caiubi, 1322 - Perdizes, São Paulo - SP",3,2,1,2800,800,Salão de festas\nPiscina\nBicicletário\nElevad...
38,70,"Rua Álvaro de Carvalho, 134 - Centro, São Paul...",2,2,1,2100,780,Piscina\nChurrasqueira\nElevador\nCondomínio f...
39,56,"Rua Jaraguá, 737 - Bom Retiro, São Paulo - SP",2,2,1,2400,430,Piscina\nElevador\nCondomínio fechado\nVaranda...
40,65,"Rua Piracuama, 417 - Perdizes, São Paulo - SP",2,1,2,1700,800,Piscina\nElevador\nAceita animais\nJardim\nSal...

In [33]:
df_sp['bairro'] = df_sp['endereco'].str.split('\-').str[1]
df_sp['bairro'] = df_sp['bairro'].str.split('\,').str[0]
df_sp.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,bairro
36,170,"Rua Cayowaá, 425 - Perdizes, São Paulo - SP",4,5,3,9500,2200,Piscina\nMobiliado\nChurrasqueira\nElevador\nA...,Perdizes
37,65,"Rua Caiubi, 1322 - Perdizes, São Paulo - SP",3,2,1,2800,800,Salão de festas\nPiscina\nBicicletário\nElevad...,Perdizes
38,70,"Rua Álvaro de Carvalho, 134 - Centro, São Paul...",2,2,1,2100,780,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Centro
39,56,"Rua Jaraguá, 737 - Bom Retiro, São Paulo - SP",2,2,1,2400,430,Piscina\nElevador\nCondomínio fechado\nVaranda...,Bom Retiro
40,65,"Rua Piracuama, 417 - Perdizes, São Paulo - SP",2,1,2,1700,800,Piscina\nElevador\nAceita animais\nJardim\nSal...,Perdizes

In [34]:
df_sp['endereco'] = df_sp['endereco'].str.split('\-').str[0]
df_sp.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,bairro
36,170,"Rua Cayowaá, 425",4,5,3,9500,2200,Piscina\nMobiliado\nChurrasqueira\nElevador\nA...,Perdizes
37,65,"Rua Caiubi, 1322",3,2,1,2800,800,Salão de festas\nPiscina\nBicicletário\nElevad...,Perdizes
38,70,"Rua Álvaro de Carvalho, 134",2,2,1,2100,780,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Centro
39,56,"Rua Jaraguá, 737",2,2,1,2400,430,Piscina\nElevador\nCondomínio fechado\nVaranda...,Bom Retiro
40,65,"Rua Piracuama, 417",2,1,2,1700,800,Piscina\nElevador\nAceita animais\nJardim\nSal...,Perdizes

In [35]:
df_sp['vagas'] = df_sp['vagas'].replace('--','0',regex=True)
df_sp.head()

,area,endereco,quartos,banheiros,vagas,preco,condominio,amenidades,bairro
36,170,"Rua Cayowaá, 425",4,5,3,9500,2200,Piscina\nMobiliado\nChurrasqueira\nElevador\nA...,Perdizes
37,65,"Rua Caiubi, 1322",3,2,1,2800,800,Salão de festas\nPiscina\nBicicletário\nElevad...,Perdizes
38,70,"Rua Álvaro de Carvalho, 134",2,2,1,2100,780,Piscina\nChurrasqueira\nElevador\nCondomínio f...,Centro
39,56,"Rua Jaraguá, 737",2,2,1,2400,430,Piscina\nElevador\nCondomínio fechado\nVaranda...,Bom Retiro
40,65,"Rua Piracuama, 417",2,1,2,1700,800,Piscina\nElevador\nAceita animais\nJardim\nSal...,Perdizes

In [36]:
df_sp['vagas'].unique()

array(['3', '1', '2', '4', '0', '5', '6', '7', '10', '26', '8', '12',
       '21', '20', '40'], dtype=object)

In [37]:
df_sp['bairro'].unique()

array([' Perdizes', ' Centro', ' Bom Retiro', ' Moema',
       ' Jardim das Perdizes', ' Chácara Santo Antônio', ' Brás',
       ' Alto da Mooca', ' Itaim Bibi', ' Vila Mariana', ' Pinheiros',
       ' Vila Moraes', ' Consolação', ' Liberdade', ' Jardim Do Tiro',
       ' Saúde', ' Vila Anastácio', ' Campo Belo', ' Alto da Lapa',
       ' Vila Congonhas', ' Santana', ' Vila Pirituba', ' Indianópolis',
       ' Jardim Vitoria Regia', ' Vila Gomes', ' Jaguaré',
       ' Jardim Anália Franco', ' Tatuapé', ' Cidade Monções',
       ' Cerqueira César', ' Vila Santa Teresa', ' Jardim Paulista',
       ' Sumaré', ' Vila Olímpia', ' Parque da Mooca', ' Chácara Inglesa',
       ' Santo Amaro', ' Santa Cecília', ' Vila Nova Conceição',
       ' Água Branca', ' Butantã', ' Jardim das Acacias', ' Vila Isa',
       ' Barra Funda', ' Vila Água Funda', ' Vila Pereira Barreto',
       ' Vila Cláudia', ' Vila Madalena', ' Brooklin', ' Bela Vista',
       ' Vila Gustavo', ' Belenzinho', ' Vila Buarque',
       ' Vila Monte Alegre', ' SP', ' Vila Clementino', ' Vila Invernada',
       ' Higienópolis', ' Vila Pirajussara', ' Parque Ipê',
       ' Real Parque', ' Japão', ' Vila Paulista', ' Pacaembu',
       ' Paraíso do Morumbi', ' Paraíso', ' Usina Piratininga',
       ' Aclimação', ' Jardim Santa Terezinha', ' República',
       ' Jardim Petrópolis', ' Interlagos', ' Vila Prudente', ' Pompeia',
       ' Morumbi', ' Tremembé', ' Chácara Santa Maria',
       ' Alto de Pinheiros', ' Santa Teresinha', ' Panamby', ' Ipiranga',
       ' Vila Carrão', ' Lauzane Paulista', ' Móoca', ' Jardim Dom Bosco',
       ' Vila Andrade', ' Cambuci', ' Vila Sônia',
       ' Jardim Independencia', ' Sumarezinho', ' Jardins',
       ' Jardim Morumbi', ' Cidade Jardim', ' Vila Mangalot',
       ' Chácara Klabin', ' Jardim Íris', ' Vila Monumento',
       ' Vila Sofia', ' Alto Da Boa Vista', ' Vila Leopoldina',
       ' Itaquera', ' Vila Esperança', ' Guarapiranga', ' Jardim Guedala',
       ' Vila Mascote', ' Mirandópolis', ' Freguesia do Ó',
       ' Vila Anglo Brasileira', ' Jardim Avelino', ' Vila Chabilândia',
       ' Vila Gomes Cardim', ' Campos Eliseos', ' Jardim Monjolo',
       ' Vila Albertina', ' Vila Gumercindo', ' Jardim Europa',
       ' Jardim Florida Paulista', ' Vila Cruzeiro', ' Jardim Vazani',
       ' Vila Guarani', ' Jabaquara', ' Vila Moinho Velho', ' Lapa',
       ' Vila Dos Remedios', ' Jardim São Luís', ' Vila Hamburguesa',
       ' Vila Zilda Tatuape', ' Campo Limpo', ' Vila Formosa',
       ' Jardim América', ' Vila Indiana', ' Vila Alexandria',
       ' Jardim Germania', ' Chácara Califórnia', ' Vila Uberabinha',
       ' Jardim Bonfiglioli', ' Vila Santa Catarina', ' Jardim da Saude',
       ' Sacomã', ' Parque Maria Helena', ' Parque Munhoz',
       ' Vila Cordeiro', ' Vila Maria', ' Jardim Londrina',
       ' Jardim das Vertentes', ' Ibirapuera', ' Pari',
       ' Jardim Marajoara', ' Jardim São Paulo',
       ' Conjunto Habitacional Padre Manoel da Nobrega', ' Vila Romana',
       ' Socorro', ' Sé', 'Vivas', ' Imirim', ' Vila Guilhermina',
       ' Jardim Helena', ' Vila Suzana', ' Jardim Umuarama',
       ' Paraisópolis', ' Vila Primavera', ' Planalto Paulista',
       ' Casa Verde', ' Vila das Mercês', ' Jardim Aricanduva',
       ' Vila Matilde', ' Granja Julieta', ' Vila Emir',
       ' Jardim Morro Verde', ' Vila Paulo Silas', ' Rio Pequeno',
       'Mirim', ' Canindé', ' Jardim Celeste', ' Vila Irmãos Arnoni',
       ' Vila Gertrudes', ' Vila Butantã', ' Bresser',
       ' Jardim Consórcio', ' Água Fria', ' Tucuruvi',
       ' Jardim São Savério', ' Morro dos Ingleses', ' Pirituba',
       ' Guaianases', ' Jardim Suzana', ' Limão', ' Bosque da Saúde',
       ' Americanópolis', ' Vila Santo Estéfano', ' Jardim Sarah',
       ' Praça da Árvore', ' Cidade Patriarca', ' Jardim Itapeva',
       ' Jardim Sônia', ' Penha', ' São Judas', ' Jardim Catanduva',
       ' Jardim Rizzo', ' Água Rasa', ' Vila Curuçá', ' Vila Santa Clara',
       ' Jardim Olympia', ' Jardim Paulistano', ' Moinho Velho',
       ' Super Quadra', ' Vila Guilherme', ' Vila Nova Manchester',
       ' Penha De Franca', ' Boaçava', ' Bela Aliança', ' Jardim Sabará',
       ' Chácara Belenzinho', ' Belém', ' Vila Regente Feijó',
       ' Jardim Boa Vista', ' Vila Cruz das Almas', ' Campo Grande',
       ' Vila Guedes', ' Jardim Nossa Senhora do Carmo',
       ' Jardim Panorama', ' Chácara Nossa Senhora do Bom Conselho ',
       ' Jardim Prudência', ' Vila Sao Francisco',
       ' Cidade São Francisco', ' Vila Moreira',
       ' Chácara Santo Antônio Zona Leste', ' Vila Castelo', ' Caxingui',
       ' Parque São Jorge', ' Parque São Domingos', ' Parque Imperial ',
       ' Nossa Senhora do Ö', ' Zona Leste ', ' Santa Ifigênia',
       'Valo Velho ', ' Jardim da Glória', ' Jardim Pinheiros',
       ' Jardim Marilu', ' Vila Amália', ' Jardim Bélgica', ' Maranhão',
       ' Jardim Aeroporto', ' Vila Mendes', ' Jardim Ubirajara',
       ' Vila Maria Alta', ' Vila Bela', 'Paus', ' Jardim Maristela ',
       ' Villaggio Panamby', ' Vila Ré', ' Vila Zelina',
       ' Vila Carmosina', ' Vila Ipojuca', ' Jaragua', ' Jardim Taquaral',
       ' Vila Firmiano Pinto', ' Jardim Elizabeth', ' Vila São Paulo',
       ' Mandaqui', ' Bortolândia', ' Jardim Leonor', ' Jardim Ampliação',
       ' Chácara Mafalda', ' Jardim Fonte do Morumbi ', ' Vila Azevedo',
       ' Vila do Encontro',
       ' Conjunto Habitacional Padre José de Anchieta', ' Vila Graciosa',
       ' Vila Dom Pedro I', ' Vila Progredior', ' Jardim Jussara',
       ' Capão Redondo', ' Parque Colonial', ' Jardim Dom José',
       ' Vila Amélia', ' Cidade Universitária', ' Vila Medeiros',
       ' Capela do Socorro', ' Vila Isolina Mazzei', ' Vila Cunha Bueno',
       ' Parque Edu Chaves', ' Jardim das Laranjeiras',
       ' Vila Independência', ' Vila Alpina', ' Vila Nova Alba',
       ' Lar São Paulo', ' Vila Mira', ' Conjunto Residencial Butantã',
       ' Vila Vera', ' Vila do Sol', ' Jardim', ' Vila Nova Cachoeirinha',
       ' Parque Mandaqui', ' Jardim Popular',
       ' Jardim Leonor Mendes de Barros ', ' Jardim Têxtil',
       ' Jardim Melo', ' Jaçanã', ' Cidade Dutra', ' Vila Arriete',
       ' Colonia ', ' Jardim Ester Yolanda', ' Jardim dos Francos',
       ' Vila Beatriz', ' Jardim Belém', ' Santa Terezinha', 'Vivas ',
       ' Vila Palmeiras', ' Vila Antonieta', ' Vila Bertioga',
       ' Jardim Vergueiro', ' Quarta Parada', ' Vila Nova',
       ' Jardim Santa Emília', ' Jardim Piqueroby', ' Chora Menino',
       ' Artur Alvim', ' Jardim Monte Alegre', ' Vila Inglesa',
       ' Jardim Ester', '84 ', ' Cursino', ' Vila Santa Cruz Zona Leste',
       ' Miami Paulista', ' Vila California', ' Jardim Belaura',
       ' Jardim Dracena', ' São Miguel Paulista', ' Parada Inglesa',
       ' Vila Arapuã', ' Vila Lageado', ' Jardim Alzira', 'te',
       ' Jardim Cotinha', ' Sítio Pinheirinho', ' Jardim Vila Formosa',
       ' Luz', ' Jardim Sul', ' Cidade Satélite Santa Bárbara',
       ' Conjunto Promorar Raposo Tavares', ' Jardim Brasil',
       ' Chácara Seis de Outubro', ' Jardim Previdência',
       ' Conjunto Residencial Jardim Canaã', ' Jardim Faria Lima',
       ' Vila Santana', ' Jardim Virgínia Bianca', 'Guaçu',
       ' Horto do Ipê', ' Parque Rebouças', ' Jardim Colombo',
       ' Aricanduva', ' Parque São Lourenço', ' Vila Germinal',
       ' Vila Robertina', ' Vila São José', ' Vila Piauí',
       ' Parque Do Carmo', ' Itaberaba', ' Limoeiro', ' Pedreira',
       ' City Jaragua', ' Vila Zilda', ' Vila Ema', ' Vila Industrial',
       ' Vila Maracanã', ' Jardim Santa Efigenia', ' Vila Paiva',
       ' Jardim Monte Kemel', ' Parque da Vila Prudente', ' Vila Prel',
       ' Jardim Umarizal', ' Jardim Imperador', ' Jardim Andaraí'],
      dtype=object)

In [38]:
df_sp.dtypes

area           int64
endereco      object
quartos       object
banheiros     object
vagas         object
preco         object
condominio    object
amenidades    object
bairro        object
dtype: object

In [39]:
cols = ['quartos','vagas','preco','condominio','banheiros']
df_sp[cols] = df_sp[cols].apply(pd.to_numeric, errors='coerce')

In [40]:
df_sp.dtypes

area            int64
endereco       object
quartos         int64
banheiros       int64
vagas           int64
preco         float64
condominio    float64
amenidades     object
bairro         object
dtype: object

In [49]:
df_sp.describe()

,area,quartos,banheiros,vagas,preco,condominio
count,7197.000000,7197.000000,7197.000000,7197.000000,7.197000e+03,7.197000e+03
mean,85.947200,2.086981,2.007781,1.346672,4.297194e+03,1.963691e+03
std,79.990803,0.885586,1.246650,1.154302,1.536143e+04,3.636825e+04
min,10.000000,1.000000,1.000000,0.000000,5.000000e+02,0.000000e+00
25%,49.000000,1.000000,1.000000,1.000000,1.890000e+03,5.110000e+02
50%,67.000000,2.000000,2.000000,1.000000,2.700000e+03,7.650000e+02
75%,98.000000,3.000000,2.000000,2.000000,4.200000e+03,1.132000e+03
max,3880.000000,6.000000,9.000000,40.000000,1.200000e+06,1.750000e+06

In [42]:
df_sp.isnull().sum()

area            0
endereco        0
quartos         0
banheiros       0
vagas           0
preco           3
condominio    350
amenidades    726
bairro          0
dtype: int64

In [43]:
df_sp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7200 entries, 36 to 7235
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   area        7200 non-null   int64
 1   endereco    7200 non-null   object
 2   quartos     7200 non-null   int64
 3   banheiros   7200 non-null   int64
 4   vagas       7200 non-null   int64
 5   preco       7197 non-null   float64
 6   condominio  6850 non-null   float64
 7   amenidades  6474 non-null   object
 8   bairro      7200 non-null   object
dtypes: float64(2), int64(4), object(3)
memory usage: 562.5+ KB

In [44]:
df_sp = df_sp.dropna(subset=['preco'])

In [46]:
df_sp = df_sp.fillna(0)

In [47]:
df_sp.isnull().sum()

area          0
endereco      0
quartos       0
banheiros     0
vagas         0
preco         0
condominio    0
amenidades    0
bairro        0
dtype: int64

In [48]:
df_sp.to_csv('dados_apartamentos_limpo.csv')